// Find TODO statements and complete them to build the interactive airline route map.

// TODO: add your uniqname to the HTML (use id #uniqname) file so that your work can be identified 

// TODO: import data using d3.csv()
const dataFile = 

const colornone = "#ccc";

// define colors for airlines, you can expand this as needed, WN is Southwest, B6 is JetBlue
const airlineColor = { WN: "orange", B6: "steelblue" };
const airlineName = { WN: "Southwest Airlines", B6: "JetBlue" };

// create options from selector that allows us to view all airlines or filter by a specific airline
const airlines = ["all", ...new Set(dataFile.map(d => d.Airline))];

// build selector from data
const select = d3.select("body")
    .insert("select", "#chart")
    .on("change", function () { draw(this.value); });

select.selectAll("option")
    .data(airlines)
    .join("option")
    .attr("value", d => d)
    .text(// TODO: build options from selector that allows us to view all airlines or filter by a specific airline);

// helper function to build outgoing links for each leaf node
function bilink(root) {
    // create a map of leaf nodes for quick lookup, using the unique ID generated by the id() function
    const map = new Map(root.leaves().map(d => [id(d), d]));

    // for each leaf node, build an outgoing array of [source, target, airline] tuples
    for (const d of root.leaves()) {
        d.outgoing = d.data.destinations
            .map(({ target, airline, targetRegion }) => [d, map.get(`root/${targetRegion}/${target}`), airline])
            .filter(([, target]) => target !== undefined);
    }

    return root;
}

// helper function to generate a unique ID for each node based on its position in the hierarchy
function id(node) {
    return `${node.parent ? id(node.parent) + "/" : ""}${node.data.name}`;
}

//rebuild hierarchy data and redraw chart on selection change
function draw(airlineFilter) {

    // filter data based on selection, if "all" is selected, use the entire dataset
    const filtered = airlineFilter === "all"
        ? dataFile
        : dataFile.filter(d => d.Airline === airlineFilter);

    // group data by source region and then by source airport
    const grouped = d3.group(filtered, d => d["Source region"], d => d["Source airport"]);

    // transform grouped data into a hierarchy format suitable for the chart
    const hierarchyData = {
        name: "root",
        children: Array.from(grouped, ([region, airports]) => ({
            name: region,
            children: Array.from(airports, ([airport, routes]) => ({
                name: airport,
                destinations: routes.map(r => ({ target: r["Destination airport"], airline: r.Airline, targetRegion: r["Destination region"] }))
            }))
        }))
    };

    document.getElementById("chart").innerHTML = "";
    document.getElementById("chart").appendChild(createChart(hierarchyData));
}

draw("all"); // initial draw


// TODO: integrate code from Observable notebook https://observablehq.com/@d3/hierarchical-edge-bundling 
// TODO: edit the tooltip to show the airport code, the region, and the number of outgoing and incoming routes for that airport
// TODO: edit link to show different colors for different airlines, you can use the airlineColor object defined above for reference
// TODO: edit overed and outed functions to highlight connected links and nodes on hover
function createChart(data) {

}