// Find TODO statements and complete them to build the interactive airline route map.
const d3 = window.d3;
// TODO: add your uniqname to the HTML (use id #uniqname) file so that your work can be identified 
d3.select("#uniqname").text("sjren");

// TODO: import data using d3.csv()
const dataFile = await d3.csv("data/routes.csv");

const colornone = "#ccc";

// define colors for airlines, you can expand this as needed, WN is Southwest, B6 is JetBlue
const airlineColor = { WN: "orange", B6: "steelblue" };
const airlineName = { WN: "Southwest Airlines", B6: "JetBlue" };

// create options from selector that allows us to view all airlines or filter by a specific airline
const airlines = ["all", ...new Set(dataFile.map(d => d.Airline))];

// build selector from data
const select = d3.select("body")
    .insert("select", "#chart")
    .on("change", function () { draw(this.value); });

select.selectAll("option")
    .data(airlines)
    .join("option")
    .attr("value", d => d)
    .text(d => d === "all" ? "All Airlines" : (airlineName[d] || d));

// helper function to build outgoing links for each leaf node
function bilink(root) {
    // create a map of leaf nodes for quick lookup, using the unique ID generated by the id() function
    const map = new Map(root.leaves().map(d => [id(d), d]));

    // for each leaf node, build an outgoing array of [source, target, airline] tuples
    for (const d of root.leaves()) {
        d.outgoing = d.data.destinations
            .map(({ target, airline, targetRegion }) => [d, map.get(`root/${targetRegion}/${target}`), airline])
            .filter(([, target]) => target !== undefined);
    }

    return root;
}

// helper function to generate a unique ID for each node based on its position in the hierarchy
function id(node) {
    return `${node.parent ? id(node.parent) + "/" : ""}${node.data.name}`;
}

//rebuild hierarchy data and redraw chart on selection change
function draw(airlineFilter) {

    // filter data based on selection, if "all" is selected, use the entire dataset
    const filtered = airlineFilter === "all"
        ? dataFile
        : dataFile.filter(d => d.Airline === airlineFilter);

    // group data by source region and then by source airport
    const grouped = d3.group(filtered, d => d["Source region"], d => d["Source airport"]);

    // transform grouped data into a hierarchy format suitable for the chart
    const hierarchyData = {
        name: "root",
        children: Array.from(grouped, ([region, airports]) => ({
            name: region,
            children: Array.from(airports, ([airport, routes]) => ({
                name: airport,
                destinations: routes.map(r => ({
                    target: r["Destination airport"],
                    airline: r.Airline,
                    targetRegion: r["Destination region"]
                }))
            }))
        }))
    };

    document.getElementById("chart").innerHTML = "";
    document.getElementById("chart").appendChild(createChart(hierarchyData));
}

draw("all"); // initial draw


// TODO: integrate code from Observable notebook https://observablehq.com/@d3/hierarchical-edge-bundling 
// TODO: edit the tooltip to show the airport code, the region, and the number of outgoing and incoming routes for that airport
// TODO: edit link to show different colors for different airlines, you can use the airlineColor object defined above for reference
// TODO: edit overed and outed functions to highlight connected links and nodes on hover
function createChart(data) {
    const width = 900;
    const radius = width / 2;

    const tree = d3.cluster()
        .size([2 * Math.PI, radius - 120]);

    const line = d3.lineRadial()
        .curve(d3.curveBundle.beta(0.85))
        .radius(d => d.y)
        .angle(d => d.x);

    const root = tree(
        bilink(
            d3.hierarchy(data)
                .sort((a, b) => d3.ascending(a.data.name, b.data.name))
        )
    );

    for (const d of root.leaves()) {
        d.incoming = [];
    }

    for (const d of root.leaves()) {
        for (const o of d.outgoing) {
            o[1].incoming.push(o);
        }
    }

    const svg = d3.create("svg")
        .attr("viewBox", [-width / 2, -width / 2, width, width])
        .attr("width", width)
        .attr("height", width)
        .style("font", "10px sans-serif");

    const link = svg.append("g")
        .attr("fill", "none")
        .selectAll("path")
        .data(root.leaves().flatMap(d => d.outgoing))
        .join("path")
        .each(function(d) { d.path = this; })
        .attr("d", ([i, o]) => line(i.path(o)))
        .attr("stroke", ([, , airline]) => airlineColor[airline] || colornone)
        .attr("stroke-opacity", 0.25)
        .attr("stroke-width", 1.5);

    const node = svg.append("g")
        .selectAll("g")
        .data(root.leaves())
        .join("g")
        .attr("transform", d => `rotate(${d.x * 180 / Math.PI - 90}) translate(${d.y},0)`);

    const label = node.append("text")
        .attr("dy", "0.31em")
        .attr("x", d => d.x < Math.PI ? 6 : -6)
        .attr("text-anchor", d => d.x < Math.PI ? "start" : "end")
        .attr("transform", d => d.x >= Math.PI ? "rotate(180)" : null)
        .text(d => d.data.name)
        .style("cursor", "pointer")
        .each(function(d) { d.text = this; })
        .on("mouseover", overed)
        .on("mouseout", outed);

    label.append("title")
        .text(d =>
            `Airport: ${d.data.name}\n` +
            `Region: ${d.parent.data.name}\n` +
            `Outgoing routes: ${d.outgoing.length}\n` +
            `Incoming routes: ${d.incoming.length}`
        );

    function overed(event, d) {
        link.attr("stroke-opacity", 0.05);

        label
            .attr("fill", null)
            .attr("font-weight", null);

        d3.select(d.text)
            .attr("font-weight", "bold")
            .attr("fill", "black");

        d.incoming.forEach(([source, , airline]) => {
            d3.select(source.text)
                .attr("font-weight", "bold")
                .attr("fill", airlineColor[airline] || "black");
        });

        d.outgoing.forEach(([, target, airline]) => {
            d3.select(target.text)
                .attr("font-weight", "bold")
                .attr("fill", airlineColor[airline] || "black");
        });

        d.incoming.forEach(l => {
            d3.select(l.path)
                .raise()
                .attr("stroke", airlineColor[l[2]] || colornone)
                .attr("stroke-opacity", 1)
                .attr("stroke-width", 2.5);
        });

        d.outgoing.forEach(l => {
            d3.select(l.path)
                .raise()
                .attr("stroke", airlineColor[l[2]] || colornone)
                .attr("stroke-opacity", 1)
                .attr("stroke-width", 2.5);
        });
    }

    function outed() {
        label
            .attr("fill", null)
            .attr("font-weight", null);

        link
            .attr("stroke", ([, , airline]) => airlineColor[airline] || colornone)
            .attr("stroke-opacity", 0.25)
            .attr("stroke-width", 1.5);
    }

    return svg.node();
}